FROM r-base
RUN cd /tmp && wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz && tar -zxvf OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz && /bin/rm -f OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz


jdk8u202-b08

